version: "3.8"

services:
  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
