version: "3.8"

services:
  # FastAPI backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - PYTHONDONTWRITEBYTECODE=1 # Don't write .pyc files
      - PYTHONUNBUFFERED=1 # Output logs immediately
    ports:
      - "5501:5501" # Use port 5501 on host to match with internal port
    volumes:
      - ./backend:/app # Mount source code for hot reload
    networks:
      - app-network
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5501", "--reload"]

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
  app-network:
    driver: bridge
