version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev # Use the development Dockerfile
    restart: always
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000" # Map port for direct API access
    volumes:
      - ./backend:/app # Mount source code for hot reload
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
